/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import com.sun.javafx.scene.control.skin.VirtualFlow;
import javax.swing.DefaultListModel;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;
import musicstreamer.MusicStreamer;
import musicstreamer.SongManager;
import musicstreamer.SongRecord;
import musicstreamer.User;

/**
 *
 * @author 018639476
 * @author 015222816
 */

class MyPlayer implements Runnable
{
    Player player;

    //recieve a javazoom.jl.player
    public MyPlayer(String songRecordId) {
        this.player = MusicStreamer.mp3play("data\\"+songRecordId+".mp3");;
    }

    public Player getPlayer() {
        return player;
    }

    public void setPlayer(Player player) {
        this.player = player;
    }

    @Override
    public void run() {
        try {
            player.play();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
}

public class UserWin extends javax.swing.JFrame {
    String currentRecordId;
    Thread thread;
    User user;
    List<SongRecord> userPlaylist;
    SongManager sm;

    /**
     * Creates new form UserWin
     */
    public UserWin(User user) {
        initComponents();
        currentRecordId = "";
        this.user = user;
        userPlaylist = new ArrayList<>();
        try{
            sm = new SongManager();
            DefaultListModel<String> listOfFavoriteSongs = new DefaultListModel<>();
            for(int i = 0; i<user.getPlayList().size(); i++)
            {
                userPlaylist.add(sm.findSongById(user.getPlayList().get(i)));
                listOfFavoriteSongs.addElement(userPlaylist.get(i).getSong().getTitle()+ " _ " + 
                    userPlaylist.get(i).getArtist().getName()+" _ "+
                    userPlaylist.get(i).getSong().getId());
            }
            playlist_UI.setModel(listOfFavoriteSongs);
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
    //function to decide to search by artist or song title
    public int searchByArtistOrName(String artistText, String titleText){
       
        //condition 1: if artist has text & title is empty
        if(!artistText.isEmpty() && titleText.isEmpty()){
            return 1;
        }
        //condition 2: if artist is empty & title has text
        else if(artistText.isEmpty() && !titleText.isEmpty()){
            return 2;
        }
        //condition 3: if artist & title has text
        else if (!artistText.isEmpty() && !titleText.isEmpty()){
           return 3; 
        }
        //condition 4: if both are empty
        else{
            return 0;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        welcomeLabel = new javax.swing.JLabel();
        playBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        songNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchArtistTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        searchTitletxt = new javax.swing.JTextField();
        WarningText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SongList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        playlist_UI = new javax.swing.JList<>();
        savePlaylistBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        artistLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        termsLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        releaseNameLabel = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setText("Welcome");

        playBtn.setText("Play");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        stopBtn.setText("Stop");
        stopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Song Name");

        songNameLabel.setText("-");

        jLabel2.setText("Search Song by Artist");

        searchBtn.setText("Search");
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        jLabel3.setText("Search Song by Title");

        WarningText.setText("-");

        SongList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SongListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(SongList);

        jButton1.setText("Add to Playlist");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        playlist_UI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playlist_UIMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(playlist_UI);

        savePlaylistBtn.setText("Save Playlist");
        savePlaylistBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savePlaylistBtnMouseClicked(evt);
            }
        });

        jLabel4.setText("Artist Name");

        artistLabel.setText("-");

        jLabel6.setText("Terms");

        termsLabel.setText("-");

        jLabel5.setText("Duration");

        durationLabel.setText("-");

        jLabel7.setText("Release Name");

        releaseNameLabel.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(savePlaylistBtn)
                .addGap(217, 217, 217))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchArtistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(searchTitletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(WarningText, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(artistLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(termsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(durationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(releaseNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(35, 35, 35)
                                        .addComponent(songNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(searchArtistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(searchTitletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBtn)
                            .addComponent(WarningText))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(songNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(artistLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(releaseNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(termsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(durationLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playBtn)
                            .addComponent(stopBtn)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savePlaylistBtn)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked

        int selection;
        // TODO add your handling code here:
         //creating string variables for artistText and nameText
        String artistText = searchArtistTxt.getText();
        String titleText = searchTitletxt.getText();
        selection = searchByArtistOrName(artistText, titleText);
            
        while (true){
            //if artist text is filled
            if(selection == 1){
                
                String message = "Searching...";
                WarningText.setText(message);
                 // implement findsongby name
                List <SongRecord> recordList = sm.findSongByArtist(artistText);
                //find song by name
                //for loop to generate multiple songs
                DefaultListModel<String> listOfSongs = new DefaultListModel<>();
                for(int i = 0; i < recordList.size(); i++){
                    listOfSongs.addElement(recordList.get(i).getSong().getTitle()+" _ "+recordList.get(i).getSong().getId());
                }
                SongList.setModel(listOfSongs);
                break;
            }
            //if name text is filled
            else if(selection == 2){
                String message = "Searching...";
                WarningText.setText(message);
                //implement findSongbyTitle
                List <SongRecord> recordList = sm.findSongByTitle(titleText);
                //find song by title
                //for loop to generate multiple song
                //connect song to search
                DefaultListModel<String> listOfSongs = new DefaultListModel<>();
                for(int i = 0; i < recordList.size(); i++){
                    listOfSongs.addElement(recordList.get(i).getSong().getTitle()+" _ "+recordList.get(i).getSong().getId());
                }
                SongList.setModel(listOfSongs);
                break;
            }
            //if both fields are filled
            else if(selection == 3){
                String message = "Error! choose only one field.";
                WarningText.setText(message);
                break;
            }
        }
    }//GEN-LAST:event_searchBtnMouseClicked

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        if(thread!=null)
        {
            thread.stop();
            thread = null;
        }
        try{
            if(currentRecordId!=null && !currentRecordId.equals(""))
            {
                MyPlayer myPlayer = new MyPlayer(currentRecordId);
                thread = new Thread(myPlayer);
                thread.start();
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }

    private void stopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnActionPerformed
        // TODO add your handling code here:
        try{
                thread.stop();
                thread = null;
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_stopBtnActionPerformed

    //add to favorite button
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String song = SongList.getSelectedValue();
        if(song!=null && !song.equals(""))
        {
            String[] attrs = song.split(" _ ");
            String id = attrs[1];
            user.getPlayList().add(id);
        }  
        DefaultListModel<String> listOfFavoriteSongs = new DefaultListModel<>();
        userPlaylist = new ArrayList<>();
        for(int i = 0; i<user.getPlayList().size(); i++)
        {
            String songId = user.getPlayList().get(i);
            userPlaylist.add(sm.findSongById(songId));
            listOfFavoriteSongs.addElement(userPlaylist.get(i).getSong().getTitle()+ " _ " + 
                userPlaylist.get(i).getArtist().getName()+" _ "+
                userPlaylist.get(i).getSong().getId());
        }
        playlist_UI.setModel(listOfFavoriteSongs);
    }//GEN-LAST:event_jButton1MouseClicked

    private void savePlaylistBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savePlaylistBtnMouseClicked
        // TODO add your handling code here:
        boolean saved = user.saveUser();
        if(saved)
            System.out.println("saved user playlist.");
        else
            System.out.println("could not save playlist!");
    }//GEN-LAST:event_savePlaylistBtnMouseClicked

    private void SongListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SongListMouseClicked
        // TODO add your handling code here:
        String songarrts = SongList.getSelectedValue();
        String[] attrs = songarrts.split(" _ ");
        currentRecordId = attrs[1];
        SongRecord sr = sm.findSongById(currentRecordId);
        songNameLabel.setText(sr.getSong().getTitle());
        artistLabel.setText(sr.getArtist().getName());
        releaseNameLabel.setText(sr.getRelease().getName());
        termsLabel.setText(sr.getArtist().getTerms());
        durationLabel.setText((sr.getSong().getDuration()/60)+" minutes");
    }//GEN-LAST:event_SongListMouseClicked

    private void playlist_UIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playlist_UIMouseClicked
        // TODO add your handling code here:
        String songarrts = playlist_UI.getSelectedValue();
        String[] attrs = songarrts.split(" _ ");
        currentRecordId = attrs[2];
        SongRecord sr = sm.findSongById(currentRecordId);
        songNameLabel.setText(sr.getSong().getTitle());
        artistLabel.setText(sr.getArtist().getName());
        releaseNameLabel.setText(sr.getRelease().getName());
        termsLabel.setText(sr.getArtist().getTerms());
        durationLabel.setText((sr.getSong().getDuration()/60)+" minutes");
    }//GEN-LAST:event_playlist_UIMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new UserWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> SongList;
    private javax.swing.JLabel WarningText;
    private javax.swing.JLabel artistLabel;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton playBtn;
    private javax.swing.JList<String> playlist_UI;
    private javax.swing.JLabel releaseNameLabel;
    private javax.swing.JButton savePlaylistBtn;
    private javax.swing.JTextField searchArtistTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTitletxt;
    private javax.swing.JLabel songNameLabel;
    private javax.swing.JButton stopBtn;
    private javax.swing.JLabel termsLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
